version:               2
jobs:
  build:
    machine:           true
    working_directory: ~/ftgo-monolith
    steps:
      - checkout
      - restore_cache:
          keys:
            - ftgo-monolith-{{ checksum "gradle.properties" }}
            - ftgo-monolith-
      - run: TERM=dumb ./gradlew testClasses componentTestClasses integrationTestClasses
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: ftgo-monolith-{{ checksum "gradle.properties" }}
      - run:
          command:     |
            ./.circleci/upgrade-docker-compose.sh
      - run:
          command:     |
            . ./setenv-circle-ci.sh
            ./build-and-test-ftgo-monolith.sh
      - run:
          command:     |
            . ./setenv-circle-ci.sh
            ./build-and-test-ftgo-microservices.sh
      - run:
          name:        Save test results
          command:     |
            mkdir -p ~/junit ~/container-logs
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
            docker ps -a > ~/container-logs/containers.txt
            sudo bash -c 'find /var/lib/docker/containers -name "*-json.log" -exec cp {} ~/container-logs \;'
            sudo bash -c 'find  ~/container-logs -type f -exec chown circleci {} \;'
          when:        always
      - store_test_results:
          path:        ~/junit
      - store_artifacts:
          path:        ~/junit
      - store_artifacts:
          path: ~/container-logs
